---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smbcredentials-coen
  namespace: democratic-csi
spec:
  encryptedData:
    mount_flags: AgBguMh1FvEeUu4TTsxzoqGr0jNO5fvF90ZSWjAZobxOzBOE6dsGnjbZys44GGR9y1kVM5gfM52qpJYxnFn7Gn3VFHI5bzcGBERTqlcaie/HCLzI6Ijuij0pQAcDubmgxrqsgat6KpJuyf3YeJJzBqdx/d6UGHL1df/FERwT3vkjqnnZuNorNMpkOzPGtO279IB8m+SL9ZaHOVTYngWCuxaQXf5+T3g/kFb2tPFUFmWEwHTkmlip3E39hWRDxjsHCi6aWD0W4z4Q6o+91aQRyWR1W5QhFbJxbxwktRd2VLUcVgCqq4LlYy8KPinNjXEvxTlKIVkM1mnTE281cJW9XtsHQMrsOhGk2ZMSZX27/HDZhBfZKjlLQmcWe+ijIFHYDfVdqbdQ7TPIpgcSMGPpF9JCF+NBLbRiKWEMblQ2Dnc8f2NvuYhkuuAKNYpqc2p9Skqma87Ha6H7/ZHQe/Ef8T1vdYTDcl9tcsWLlSfbnnU1Dzr7SUalVHPWLrG1lsuP7doMwL/vfPjslMn8+Yn5aMUZPs/FPIWZ+Q7/clS0d0rxCGWZLj6BEc/hoAne/KxGSdau4oCOPtBGgsNGCuQJv5KMmVb4K78f/tweHjnKYEaBG69+Vkx62dZbxhqyfBRpxhvTUxA29QKj81SKgV/cfe3RpgVmBHU7NV+4fg70lc12WyWLnG78NvcliLtkkNxcWPZ+IhI+4jr9nu8ejoMzteHpLOMm
  template:
    metadata:
      creationTimestamp: null
      name: smbcredentials-coen
      namespace: democratic-csi
