---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret-env
  namespace: tools
spec:
  encryptedData:
    DB_PASSWORD: AgALYYjHBWHt0zkP1Hi4I9VVAl8ALpaTkH2HWK5OBU3PODE8p39kozoExKxCcZY2opQKyB1McPbDHeTuUreLQaTqEIRYZ+aJKgcci7CJyYJc/tgrIcY17AFb87bEXJIqSjDOxgqwAU30jd0EANJJ0HS26fWB3UHWPtWAdFmjSKNE+qbbcO5P7xQcLHmip2iVNrgqrXHoOyUnvYbJym5SRuKOQMTHPKRay63dp2GmTPfrZZoeqMITqPWm7AAaaZsLlS4vcOVubV9gOsEsMKs8CHyDvcXuXBHQlJmf9tqrr7QyINGyjFERYfKbcjp+DEeF9xjnXi9kls8X0oSs0/Rq6q4H0i0JaEPQvUYRPrf0gd42V8FUj1TGLeIoVukUFbFvKdr3Gb2gREaHnBZH5GE9yTyc4blGhkuykWspw4bz1mdmFR1I8rnckfkueVvdTvHJXWsaU/B4+pZl3nV+v1qbCxbMHuA5ulWsNRnf5I853EYukjc6/KKBTRKJpi+KcUFccM6F5a87TZ0cCONUAvQ3Hww158sn4pf+ZO4b1V3BGMEeqnPtFqQMVkUM+Vc3JzQ9+c3Nr20qQ9YqLA8KGkzt0r5cZLfu+PiL8s5FN7/Ug+jyhkIxPA5R29BoS2vQSjt1fN8tR+cZIDyyyLP0DQs2/kMN8bUT2TOKjPgVrHdMsABbk2YcEx92zEqBSGwNhrW3QP9ZAN6kKzEqTkI=
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret-env
      namespace: tools
